[project]
name = "nym"
version = "0.3.0"
description = "No, Yes, Maybe?"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "pyperclip>=1.9.0",
    "textual>=3.1.0",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
